const enMessages = {
  'header.theme-switcher.light': 'Light',
  'header.theme-switcher.dark': 'Dark',
  'main.banner.heading-size-l': 'Create, manage, share',
  'main.banner.heading-size-m': 'everything from a single place',
  'main.banner.form-message.start': "Register a new account if you're a newcomer here or just ",
  'main.banner.form-message.link': ' Sign in ',
  'main.banner.form-message.end': 'if you already have an account',
  'main.banner.auth-form.login': 'Sign in',
  'main.banner.auth-form.signup': 'Sign up',
  'main.items.heading': 'Recently added',
  'main.items.info.start': 'Added by',
  'main.items.info.end': 'on',
  'main.collections.heading': 'Largest collections',
  'main.collections.stat': 'Volume',
  'main.collections.link': 'View',
  'main.search-results.message': 'Elements found',
  'main.item.info.start': 'Added',
  'main.item.info.end': 'by',
  'main.collection.author': 'Author',
  'main.collection.category': 'Category',
  'main.collection.table.title': 'Collection items',
  'main.collection.table.col-1': 'Name',
  'main.collection.table.col-2': 'Tags',
  'main.collection.table.col-3': 'Created on',
  'main.collection.table.filter.day': 'last 24 hours',
  'main.collection.table.filter.week': 'week',
  'main.collection.table.filter.month': 'month',
  'footer.quote': 'Collecting means being able to live in the past. (Albert\u00a0Camus)',
};

const ruMessages = {
  'header.theme-switcher.light': 'Светлая',
  'header.theme-switcher.dark': 'Темная',
  'main.banner.heading-size-l': 'Создавай и делись',
  'main.banner.heading-size-m': 'всё собрано в одном месте',
  'main.banner.form-message.start': 'Зарегистрируйте новый аккаунт или попробуйте',
  'main.banner.form-message.link': ' Войти ',
  'main.banner.form-message.end': 'в личный кабинет если у вас уже есть аккаунт',
  'main.banner.auth-form.login': 'Войти',
  'main.banner.auth-form.signup': 'Зарегистрироваться',
  'main.items.heading': 'Новинки',
  'main.items.info.start': 'Добавил',
  'main.items.info.end': ' ',
  'main.collections.heading': 'Крупнейшие коллекции',
  'main.collections.stat': 'Количество',
  'main.collections.link': 'Смотреть',
  'main.search-results.message': 'Найдено элементов',
  'main.item.info.start': 'Добавлено',
  'main.item.info.end': 'пользователем',
  'main.collection.author': 'Автор',
  'main.collection.category': 'Категория',
  'main.collection.table.title': 'Экземпляры коллекции',
  'main.collection.table.col-1': 'Название',
  'main.collection.table.col-2': 'Тэги',
  'main.collection.table.col-3': 'Добавлено',
  'main.collection.table.filter.day': 'за последние 24 часа',
  'main.collection.table.filter.week': 'неделю',
  'main.collection.table.filter.month': 'месяц',
  'footer.quote': 'Коллекционировать — значит уметь жить прошлым. (Альбер\u00a0Камю)',
};

export { enMessages, ruMessages };
