const items = [
  {
    id: 1,
    type: "item",
    name: "Носки белые",
    description: "",
    tags: ["clothes", "white"],
    comments: ["Абы что."],
    likesCount: 0,
    url: "",
    collection: { id: 4, name: "Носки", owner: "superuser" },
    createdOn: "2022-10-12",
  },
  {
    id: 2,
    type: "item",
    name: "Носки серые",
    description: "",
    tags: ["gray"],
    comments: [],
    likesCount: 0,
    url: "",
    collection: { id: 4, name: "Носки", owner: "superuser" },
    createdOn: "2022-10-12",
  },
  {
    id: 3,
    type: "item",
    name: "Первый человек",
    description: "Неоконченный автобиографический роман Альбера Камю.",
    tags: ["биография", "Камю"],
    comments: [],
    likesCount: 10,
    url: "/files/premier.jpg",
    collection: { id: 5, name: "Книги Альбера Камю", owner: "superuser" },
    createdOn: "2022-10-14",
  },
  {
    id: 4,
    type: "item",
    name: "Посторонний",
    description: "Дебютный роман Альбера Камю.",
    tags: ["камю", "французская литература"],
    comments: [
      "Несмотря на то, что указанное творение является первым по-настоящему весомым его произведением, именно его я бы позволил себе считать magnum opus всего творчества Камю.",
      "Торжество абсурда во всей своей непередаваемой красоте.",
    ],
    likesCount: 5,
    url: "/files/etranger.jpg",
    collection: { id: 5, name: "Книги Альбера Камю", owner: "superuser" },
    createdOn: "2022-10-19",
  },
  {
    id: 5,
    type: "item",
    name: "Чума",
    description: "Роман французского писателя Альбера Камю.",
    tags: ["книги", "Камю", "классика", "популярное", "литература"],
    comments: ["Классная книга!", "Прочел, ничего не понял"],
    likesCount: 42,
    url: "/files/peste.jpg",
    collection: { id: 5, name: "Книги Альбера Камю", owner: "superuser" },
    createdOn: "2022-10-19",
  }
];

module.exports = items;
