name: app CI
on: push
jobs:
  code-check:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: repo cloning
        uses: actions/checkout@v3
      - name: deps installation
        run: npm ci
      - name: tests & linting
        env:
          CI: true
        run: |
          npm run lint
          npm run test
      